### ISSUE TITLE
About experiments

### ISSUE THREAD

**Issue by Zizzzzzzz** [CASR-HKU/DSEC-MOT#1]
Thank you for providing the first event-based multi-object tracking dataset. I have two questions regarding the experimental section: (1) What is the resolution of the model input? Is it 640*480? (2) In the comparison methods you mentioned, did you follow the original training strategy, including retaining the data augmentation methods and pretrained model they used?

**Comment by wshku** [comment]
Thank you for your interest in our work. (1) Yes, the input resolution is 640 x 480. (2) All the methods we compared utilize the official code and adhere to the original strategy, which includes using the original data augmentation techniques and their pre-trained model.
