### ISSUE TITLE
About labels

### ISSUE THREAD

**Issue by Zizzzzzzz** [CASR-HKU/DSEC-MOT#2]
I notice that when the object is relatively stationary with respect to the event camera, its bounding box is lost. Is this designed intentionally? For example, the car at the center of the image.
![image](https://github.com/CASR-HKU/DSEC-MOT/assets/88081108/abc8aa3a-7a61-4fb5-99ac-abb359d6af1c)
![image](https://github.com/CASR-HKU/DSEC-MOT/assets/88081108/944fab85-831c-4f4d-bc82-2417c00c04ab)

**Comment by wshku** [comment]
It is designed intentionally. When an object is stationary relative to the event camera, little event will be produced from its motion, causing it to disappear from the scene. As mentioned in the section of Labeling Protocol of our paper, these disappeared objects are exempted from annotation, according to their attributes under such conditions.
